[package]
name = "merry-py"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
publish = false

[lib]
name = "_merry"
crate-type = ["cdylib", "rlib"]

[dependencies]
futures-executor.workspace = true
futures-core.workspace = true
futures-util.workspace = true
merry-core = { path = "../merry-core" }
merry-llm = { path = "../merry-llm", features = ["test-utils"] }
merry = { path = "../merry" }
merry-runtime = { path = "../merry-runtime" }
pyo3.workspace = true
schemars.workspace = true
serde.workspace = true
serde_json.workspace = true
tokio = { workspace = true, features = ["rt"] }
tokio-util.workspace = true

[lints]
workspace = true
