from collections.abc import Awaitable

class NativeMerryError(Exception):
    """Rust-originated error carrying a serialized MerryErrorInfo payload."""

class AgentBuilder:
    def __init__(self, session_id: str) -> None: ...
    def with_openai_compatible(
        self,
        api_key: str,
        model: str,
        base_url: str | None,
        protocol: str,
    ) -> None: ...
    def with_anthropic(
        self, api_key: str, model: str, base_url: str | None
    ) -> None: ...
    def with_workspace(
        self,
        roots: list[str],
        readonly_resource_roots: list[str],
        allow_hidden: bool,
        enable_patch: bool,
        patch_write_scope: list[str] | None,
        forbidden_paths: list[str],
        max_read_bytes: int,
        max_write_bytes: int,
        max_patch_bytes: int,
        max_list_entries: int,
        max_search_matches: int,
        max_search_files: int,
        max_search_entries: int,
        max_search_bytes: int,
        max_search_line_bytes: int,
        max_search_query_bytes: int,
    ) -> None: ...
    def register_bridge_tool(
        self, name: str, description: str, schema_json: str
    ) -> None: ...
    def with_session_store(self, path: str) -> None: ...
    def with_max_model_turns(self, value: int) -> None: ...
    def with_event_buffer_size(self, value: int) -> None: ...
    def build(self) -> Agent: ...
    def resume(self, path: str | None = None) -> Awaitable[Agent]: ...
    def is_consumed(self) -> bool: ...

class Agent:
    def session_id(self) -> str: ...
    def stream(self, task: str, final_output_schema_json: str | None) -> AgentRun: ...
    def save_session(self) -> Awaitable[None]: ...

class AgentRun:
    def next(self) -> Awaitable[str | None]: ...
    def submit_tool_results(
        self, batch_id: str, results_json: str
    ) -> Awaitable[str]: ...
    def result(self) -> Awaitable[str]: ...
    def cancel(self) -> Awaitable[str]: ...

def version() -> str: ...
