[package]
name = "merry"
version.workspace = true
edition.workspace = true
rust-version.workspace = true

[dependencies]
merry-core = { path = "../merry-core", version = "0.1.0" }
merry-coding = { path = "../merry-coding", version = "0.1.0" }
merry-llm = { path = "../merry-llm", version = "0.1.0" }
merry-process = { path = "../merry-process", version = "0.1.0" }
merry-provider-anthropic = { path = "../merry-provider-anthropic", version = "0.1.0" }
merry-provider-openai = { path = "../merry-provider-openai", version = "0.1.0" }
merry-runtime = { path = "../merry-runtime", version = "0.1.0" }
thiserror.workspace = true

[dev-dependencies]
futures-util.workspace = true
tempfile.workspace = true

[lints]
workspace = true
