[package]
name = "merry-llm"
version.workspace = true
edition.workspace = true
rust-version.workspace = true

[features]
test-utils = []

[dependencies]
futures-core.workspace = true
futures-util.workspace = true
merry-core = { path = "../merry-core" }
schemars.workspace = true
serde.workspace = true
serde_json.workspace = true
thiserror.workspace = true
tokio.workspace = true
tokio-util.workspace = true

[dev-dependencies]
futures-executor.workspace = true
futures-util.workspace = true

[lints]
workspace = true
